version: "3.8"
services:
  react:
    container_name: ${APPLICATION_CONTAINER}
    env_file: ./.env
    restart: unless-stopped
    build:
      context: ./react
    environment:
      - REACT_APP_FRONTEND_HOST=${FRONTEND_HOST}
      - REACT_APP_BACKEND_HOST=${BACKEND_HOST}
      - REACT_APP_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    volumes:
      - ./react:/var/www/app
      - /var/www/app/node_modules
    ports:
      - "${PORT}:${PORT}"
    healthcheck:
      test: curl --fail http://localhost:${PORT} || exit 1
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s
    expose:
      - "${PORT}"

  nginx:
    container_name: ${NGINX_CONTAINER}
    restart: always
    build:
      context: ./nginx
    environment:
      - PROXY_HOST=${APPLICATION_CONTAINER}
      - PROXY_PORT=${PORT}
    ports:
      - "${NGINX_PORT}:80"
    expose:
      - "${NGINX_PORT}"
    depends_on:
      - "react"

  playwright:
    container_name: elcap_test
    profiles:
      - "test"
    depends_on:
      react:
        condition: service_healthy
    build:
      context: ./playwright
    environment:
      - REACT_APP_FRONTEND_HOST=${APPLICATION_CONTAINER}
      - REACT_APP_FRONTEND_PORT=${PORT}
    volumes:
      - ./test-report:/var/www/app/playwright-report
      - /var/www/app/node_modules
volumes:
  react-data:
  test-report:
