# base image
FROM node:16-alpine as builder

# set working directory
WORKDIR /app

# First copy only package.json & install then copy all and build
COPY ./package.json ./
COPY ./yarn.lock ./
RUN yarn
COPY . ./
RUN yarn build


# Stage 1, based on Nginx, to have only the compiled app, ready for production with Nginx
FROM nginx:1.23-alpine
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
